package org.ayeseeem.say.java.util;

class DummyValue {

    private final int value;

    private DummyValue(int value) {
        this.value = value;
    }

    static DummyValue dummy(int value) {
        return new DummyValue(value);
    }

    // auto-generated by Eclipse

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + value;
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (!(obj instanceof DummyValue)) {
            return false;
        }
        DummyValue other = (DummyValue) obj;
        if (value != other.value) {
            return false;
        }
        return true;
    }

}
